
department_keywords = {
    'HR': ['Payroll', 'Benefits', 'Recruitment', 'Onboarding', 'Employee Engagement', 'Performance Management', 'Training and Development', 'Workforce Planning', 'HR Policies', 'Talent Acquisition', 'Compensation', 'Succession Planning', 'Diversity and Inclusion', 'Labor Relations', 'Organizational Development', 'Employee Relations', 'Health and Safety', 'HR Analytics', 'Employee Retention', 'Work-Life Balance', 'Job Analysis', 'HRIS', 'Performance Appraisal', 'HR Compliance', 'Employment Law', 'Training Needs Analysis', 'Employee Wellness', 'Job Descriptions', 'Career Development', 'HR Metrics', 'Employment Contracts', 'Exit Interviews', 'HR Technology', 'Employment Equity', 'Employee Handbook', 'HR Strategy', 'Job Evaluation', 'HR Consulting', 'Employee Benefits', 'HR Budgeting', 'Employee Surveys'],
    'SM': ['Lead Generation', 'Customer Acquisition', 'Conversion Rate', 'Campaign Analytics', 'SEO', 'SEM', 'Social Media Marketing', 'Email Marketing', 'Content Marketing', 'Market Research', 'Brand Management', 'Digital Advertising', 'Customer Relationship Management', 'Sales Funnel', 'Marketing Automation', 'Influencer Marketing', 'Public Relations', 'Marketing Strategy', 'Product Launch', 'Competitive Analysis', 'Market Segmentation', 'Advertising ROI', 'Customer Retention', 'Copywriting', 'Sales Enablement', 'Google Analytics', 'Marketing Budget', 'B2B Marketing', 'B2C Marketing', 'Marketing Metrics', 'Marketing Analytics', 'Customer Persona', 'Sales Forecasting', 'Market Trends', 'Marketing Campaign', 'Customer Insights', 'Social Media Analytics', 'Marketing Communications', 'Marketing ROI', 'Online Advertising', 'Customer Engagement'],
    'FA': ['Budgeting', 'Financial Analysis', 'Cash Flow Management', 'Taxation', 'Auditing', 'Risk Management', 'Financial Reporting', 'Forecasting', 'Cost Accounting', 'Investment Analysis', 'Bookkeeping', 'Financial Modeling', 'Variance Analysis', 'Financial Planning', 'Account Reconciliation', 'Internal Controls', 'Tax Planning', 'Corporate Finance', 'Financial Statements', 'Asset Management', 'Managerial Accounting', 'Financial Audits', 'Capital Budgeting', 'Financial Ratios', 'Expense Management', 'Cost Control', 'Financial Compliance', 'Financial Markets', 'Payroll Processing', 'Credit Analysis', 'Economic Analysis', 'Cash Management', 'Tax Compliance', 'Financial Systems', 'Business Valuation', 'Accounts Payable', 'Accounts Receivable', 'Financial Governance', 'Financial Risk', 'Treasury Management', 'Financial Policies'],
    'OP': ['Supply Chain Management', 'Inventory Control', 'Logistics', 'Quality Assurance', 'Process Optimization', 'Workflow Automation', 'Production Planning', 'Project Management', 'Lean Manufacturing', 'Six Sigma', 'Demand Planning', 'Vendor Management', 'Capacity Planning', 'Operations Research', 'Continuous Improvement', 'Facilities Management', 'Productivity Enhancement', 'Procurement', 'Scheduling', 'Quality Control', 'Warehouse Management', 'Operations Strategy', 'Performance Measurement', 'Material Planning', 'Order Fulfillment', 'Value Stream Mapping', 'Operational Efficiency', 'Maintenance Management', 'Just-in-Time (JIT)', 'Product Lifecycle Management', 'Operations Analytics', 'Process Mapping', 'Root Cause Analysis', 'Operational Risk', 'Equipment Maintenance', 'Change Management', 'Production Control', 'Service Operations', 'Supply Chain Analytics', 'Resource Allocation'],
    'IT': ['System Administration', 'Network Security', 'Database Management', 'Web Development', 'Software Development', 'Cloud Computing', 'Data Analytics', 'Cybersecurity', 'IT Infrastructure', 'IT Strategy', 'IT Governance', 'IT Service Management', 'IT Operations', 'IT Support', 'ITIL', 'DevOps', 'Agile Methodology', 'IT Project Management', 'IT Risk Management', 'IT Audits', 'IT Compliance', 'IT Architecture', 'Data Privacy', 'Business Continuity', 'IT Budgeting', 'IT Vendor Management', 'IT Performance', 'IT Outsourcing', 'IT Training', 'IT Disaster Recovery', 'IT Change Management', 'IT Asset Management', 'IT Help Desk', 'IT Policies', 'IT Documentation', 'IT Security'],
    'CS': ['Customer Service', 'Ticketing System', 'Service Level Agreement', 'Call Center', 'Customer Satisfaction', 'Complaint Resolution', 'Support Tickets', 'Live Chat', 'CRM', 'Customer Experience', 'Customer Retention', 'Customer Success', 'Customer Feedback', 'Customer Loyalty', 'Customer Support', 'Service Desk', 'Customer Complaints', 'Customer Onboarding', 'Customer Journey', 'Customer Relationship', 'Customer Advocacy', 'Customer Analytics', 'Customer Service Metrics', 'Customer Centricity', 'Customer Communication', 'Customer Needs', 'Service Quality', 'Customer Empathy', 'Customer Interaction', 'Customer Database', 'Customer Churn', 'Customer Complaint Resolution', 'Customer Engagement', 'Customer Surveys', 'Service Recovery', 'Customer Service Training', 'Voice of the Customer', 'Customer Service Automation'],
    'RD': ['Research and Development', 'Prototype Development', 'Testing and Validation', 'Data Analysis', 'Experimentation', 'Innovation', 'Intellectual Property', 'Research Collaboration', 'Technology Evaluation', 'Product Research', 'Market Research', 'Product Design', 'Ideation', 'Product Testing', 'Research Ethics', 'Research Methods', 'Data Mining', 'Data Visualization', 'Research Grants', 'Patent Analysis', 'Research Proposals', 'Experimental Design', 'Research Publications', 'Invention Disclosure', 'Research Funding', 'Research Compliance', 'Research Planning', 'Research Strategy', 'Research Reports', 'Scientific Method', 'Research Ethics', 'Research Metrics', 'Scientific Papers', 'Research Presentation', 'Qualitative Research', 'Quantitative Research', 'Research Grants', 'Research Partnerships', 'Research Collaboration'],
    'LC': ['Legal and Compliance', 'Contracts', 'Intellectual Property', 'Compliance Audits', 'Data Privacy', 'Regulatory Requirements', 'Legal Documentation', 'Risk Mitigation', 'Corporate Governance', 'Contract Management', 'Legal Research', 'Contract Negotiation', 'Contract Review', 'Corporate Law', 'Intellectual Property Rights', 'Compliance Management', 'Data Protection', 'Privacy Policies', 'Legal Compliance', 'Anti-Money Laundering', 'Ethics and Compliance', 'Regulatory Compliance', 'Legal Counsel', 'Legal Advice', 'Legal Disputes', 'Legal Agreements', 'Risk Assessment', 'Litigation Management', 'Legal Contracts', 'Employment Law Compliance', 'Legal Writing', 'Trademark Registration', 'Copyright Law', 'Patent Law', 'Corporate Policies', 'Legal Procedures', 'Legal Investigations', 'Legal Training'],
    'QA': ['Quality Assurance', 'Quality Control', 'Quality Management', 'Testing and Inspection', 'Quality Standards', 'Quality Metrics', 'Process Improvement', 'Defect Management', 'Root Cause Analysis', 'Quality Audits', 'Statistical Process Control', 'Six Sigma', 'ISO Standards', 'Lean Manufacturing', 'Continuous Improvement', 'Risk Assessment', 'Failure Analysis', 'Quality Tools', 'Supplier Quality', 'Product Development', 'Quality Planning', 'Quality Training', 'Quality Documentation', 'Corrective Actions', 'Preventive Actions', 'Process Capability', 'Gage R&R', 'Quality Assurance Systems', 'Quality Assurance Plans', 'Quality Assurance Testing', 'Quality Assurance Metrics', 'Quality Assurance Strategies', 'Quality Assurance Framework', 'Quality Assurance Guidelines', 'Quality Assurance Procedures', 'Quality Assurance Methodology', 'Quality Assurance Compliance'],
    'BD': ['Business Development', 'Market Research', 'Partnership Development', 'Lead Generation', 'Sales Strategies', 'Market Analysis', 'Competitive Analysis', 'Negotiation Skills', 'Client Relationship Management', 'Sales Presentations', 'Account Management', 'Strategic Planning', 'Client Acquisition', 'Revenue Growth', 'Customer Needs Assessment', 'Business Networking', 'Sales Pipeline Management', 'Consultative Selling', 'Proposal Writing', 'Contract Negotiation', 'Product Knowledge', 'Market Segmentation', 'Value Proposition', 'Business Planning', 'Sales Training', 'Client Retention', 'CRM', 'Business Expansion', 'Cold Calling', 'Key Account Management', 'Market Trends', 'Sales Forecasting', 'Business Analytics', 'B2B Sales', 'B2C Sales', 'Sales Performance', 'Sales Territory', 'Customer Relationship', 'Sales Metrics'],
    'PR': ['Public Relations', 'Media Relations', 'Press Releases', 'Brand Management', 'Corporate Communications', 'Crisis Management', 'Event Planning', 'Social Media Management', 'Content Creation', 'Influencer Marketing', 'Reputation Management', 'Stakeholder Engagement', 'Brand Awareness', 'Publicity', 'Digital Marketing', 'Community Relations', 'Internal Communications', 'Executive Positioning', 'Media Monitoring', 'PR Strategy', 'Press Conferences', 'Marketing Communications', 'Public Speaking', 'Media Interviews', 'Public Opinion', 'Thought Leadership', 'Brand Identity', 'Crisis Communication', 'Media Planning', 'Content Distribution', 'PR Campaigns', 'Social Listening', 'Online Reputation Management', 'Industry Analyst Relations', 'PR Metrics', 'Media Relations Training', 'Message Development', 'Event Management'],
    'ED': ['Education and Training', 'Training Needs Analysis', 'Curriculum Development', 'Instructional Design', 'Training Delivery', 'E-Learning', 'Training Evaluation', 'Learning Management Systems', 'Employee Training', 'Leadership Development', 'Onboarding Programs', 'Professional Development', 'Performance Improvement', 'Training ROI', 'Competency Assessment', 'Training Workshops', 'Blended Learning', 'Talent Development', 'Training Metrics', 'Learning Styles', 'Knowledge Transfer', 'Training Technologies', 'Training Budget', 'Training Documentation', 'Virtual Training', 'Training Facilitation', 'Training Programs', 'Skills Development', 'Coaching and Mentoring', 'Learning Analytics', 'Training Needs Assessment', 'Training Strategies', 'Organizational Learning', 'Training Compliance', 'Train-the-Trainer', 'Career Training'],
    'AD': ['Administration', 'Office Management', 'Calendar Management', 'Meeting Coordination', 'Travel Arrangements', 'Document Preparation', 'Data Entry', 'Records Management', 'Correspondence', 'Filing Systems', 'Office Supplies Management', 'Vendor Coordination', 'Event Planning', 'Budget Management', 'Executive Support', 'Project Coordination', 'Database Management', 'Report Generation', 'Presentation Preparation', 'Time Management', 'Email Management', 'Scheduling', 'Office Policies', 'Administrative Support', 'Resource Allocation', 'Task Prioritization', 'Proofreading and Editing', 'Interdepartmental Communication', 'Workflow Optimization', 'Administrative Procedures', 'Confidentiality', 'Office Equipment Maintenance', 'Policy Implementation', 'Office Technology', 'Information Management', 'Invoice Processing', 'Administrative Systems'],
    'PRD': ['Product Management', 'Product Development', 'Market Research', 'Product Strategy', 'Product Roadmap', 'Product Launch', 'Product Lifecycle', 'Competitive Analysis', 'Market Analysis', 'User Research', 'Requirements Gathering', 'Product Planning', 'Agile Methodology', 'Scrum', 'User Experience', 'User Interface', 'Prototyping', 'Wireframing', 'Product Metrics', 'Product Marketing', 'Go-to-Market Strategy', 'Product Positioning', 'Product Pricing', 'Product Requirements', 'Product Design', 'Product Testing', 'Product Documentation', 'Product Innovation', 'Product Analytics', 'Product Sales', 'Product Training', 'Product Quality', 'Product Scalability', 'Product Monetization', 'Product Performance', 'Product Launches', 'Product Feedback', 'Product Strategy Alignment', 'Product Vision'],
    'ADM': ['Advertising and Media', 'Media Planning', 'Advertising Campaigns', 'Creative Direction', 'Copywriting', 'Graphic Design', 'Digital Advertising', 'Print Advertising', 'Media Buying', 'Brand Awareness', 'Media Strategy', 'Content Creation', 'Social Media Advertising', 'Online Advertising', 'TV Advertising', 'Radio Advertising', 'Outdoor Advertising', 'Advertising ROI', 'Ad Placement', 'Campaign Tracking', 'Market Research', 'Audience Targeting', 'Advertising Budget', 'Branding', 'Advertising Metrics', 'Ad Campaign Analysis', 'Advertising Trends', 'Media Relations', 'Media Partnerships', 'Ad Creative', 'Brand Messaging', 'Influencer Marketing', 'Media Monitoring', 'Native Advertising', 'Product Placement', 'Ad Production', 'Ad Testing'],
    'CSM': ['Customer Success Management', 'Customer Onboarding', 'Customer Engagement', 'Customer Retention', 'Customer Satisfaction', 'Customer Advocacy', 'Customer Support', 'Account Management', 'Upselling and Cross-selling', 'Customer Feedback', 'Churn Prevention', 'Renewal Management', 'Customer Training', 'Customer Health Monitoring', 'Customer Journey Mapping', 'Customer Success Metrics', 'Business Reviews', 'Customer Success Strategies', 'Customer Segmentation', 'Customer Data Analysis', 'Customer Expansion', 'Customer Enablement', 'Customer Success Tools', 'Customer Success Operations', 'Customer Success Planning', 'Customer Success Culture', 'Customer Success Communication', 'Customer Success Automation', 'Customer Success KPIs', 'Customer Success Frameworks', 'Customer Success Dashboards', 'Customer Success Training', 'Customer Success Collaboration'],
    'CYB': ['Cybersecurity', 'Information Security', 'Vulnerability Assessment', 'Penetration Testing', 'Network Security', 'Security Incident Response', 'Security Operations Center', 'Threat Intelligence', 'Security Audits', 'Identity and Access Management', 'Data Encryption', 'Firewalls', 'Intrusion Detection and Prevention', 'Security Policies', 'Risk Assessment', 'Security Awareness Training', 'Security Governance', 'Malware Analysis', 'Incident Handling', 'Security Architecture', 'Security Monitoring', 'Data Privacy', 'Cyber Threats', 'Security Standards', 'Endpoint Security', 'Cloud Security', 'Web Application Security', 'Security Compliance', 'Cybersecurity Frameworks', 'Forensics Analysis', 'Security Incident Management', 'Security Assessments', 'Security Controls', 'Security Assessments', 'Network Monitoring', 'Security Testing', 'Security Awareness']
}

department_impact = {
    'HR': 0.2,
    'SM': 0.5,
    'FA': 0.3,
    'OP': 0.5,
    'IT': 1.0,
    'CS': 0.2,
    'RD': 0.4,
    'LC': 0.4,
    'QA': 0.2,
    'BD': 0.2,
    'PR': 0.2,
    'ED': 0.2,
    'AD': 0.2,
    'PRD': 0.4,
    'ADM': 0.2,
    'CSM': 0.2,
    'CYB': 1.0
}

employment_status_keywords = {
    'CEO': ['Chief Executive Officer', ' CEO'],
    'CTO': ['Chief Technology Officer',' CTO'],
    'CFO': ['Chief Financial Officer',' CFO'],
    'COO': ['Chief Operating Officer', ' COO'],
    'CMO': ['Chief Marketing Officer', ' CMO'],
    'CSO': ['Chief Strategy Officer', ' CSO'],
    'CIO': ['Chief Information Officer', ' CIO'],
    'SVP': ['Senior Vice President',' SVP'],
    'VP': ['Vice President',' VP'],
    'Director': ['Director'],
    'Manager': ['Manager'],
    'Supervisor': ['Supervisor'],
    'Team Lead': ['Team Lead'],
    'Engineer': ['Engineer'],
    'Analyst': ['Analyst'],
    'Specialist': ['Specialist'],
    'Coordinator': ['Coordinator'],
    'Associate': ['Associate'],
    'Assistant': ['Assistant'],
    'Intern': ['Intern'],
    'Contractor': ['Contractor'],
    'Consultant': ['Consultant'],
    'Freelancer': ['Freelancer'],
    'Advisor': ['Advisor'],
    'Executive': ['Executive'],
    'Administrator': ['Administrator'],
    'Officer': ['Officer'],
    'Architect': ['Architect'],
    'Designer': ['Designer'],
    'Developer': ['Developer'],
    'Researcher': ['Researcher'],
    'Scientist': ['Scientist'],
    'Technician': ['Technician'],
    'Operator': ['Operator'],
    'Support': ['Support'],
    'Sales': ['Sales'],
    'Marketing': ['Marketing'],
    'Human Resources': ['Human Resources'],
    'Finance': ['Finance'],
    'Legal': ['Legal'],
    'Quality Assurance': ['Quality Assurance'],
    'Customer Service': ['Customer Service'],
    'Operations': ['Operations'],
    'Business Development': ['Business Development'],
    'Product Management': ['Product Management'],
}

employment_status_importance = {
    'CEO': 10,
    'CTO': 9,
    'CFO': 8,
    'COO': 8,
    'CMO': 7,
    'CSO': 7,
    'CIO': 7,
    'SVP': 6,
    'VP': 6,
    'Director': 5,
    'Manager': 4,
    'Supervisor': 4,
    'Team Lead': 4,
    'Engineer': 5,
    'Analyst': 5,
    'Specialist': 5,
    'Coordinator': 4,
    'Associate': 3,
    'Assistant': 3,
    'Intern': 2,
    'Contractor': 3,
    'Consultant': 3,
    'Freelancer': 3,
    'Advisor': 3,
    'Executive': 4,
    'Administrator': 4,
    'Officer': 4,
    'Architect': 5,
    'Designer': 5,
    'Developer': 5,
    'Researcher': 5,
    'Scientist': 5,
    'Technician': 4,
    'Operator': 3,
    'Support': 3,
    'Sales': 3,
    'Marketing': 3,
    'Human Resources': 3,
    'Finance': 4,
    'Legal': 4,
    'Quality Assurance': 6,
    'Customer Service': 3,
    'Operations': 4,
    'Business Development': 4,
    'Product Management': 5
}

education_keyword_ratings = {
    'Accounting': 8,
    'Advertising': 7,
    'Aerospace': 6,
    'Agriculture': 7,
    'Analytics': 8,
    'Architecture': 9,
    'Artificial Intelligence': 10,
    'Banking': 7,
    'Biochemistry': 8,
    'Biology': 8,
    'Biotechnology': 8,
    'Business': 9,
    'Chemical Engineering': 8,
    'Chemistry': 8,
    'Civil Engineering': 8,
    'Communications': 7,
    'Computer Science': 10,
    'Construction': 7,
    'Consulting': 8,
    'Creative Writing': 6,
    'Cybersecurity': 9,
    'Data Analysis': 8,
    'Data Science': 9,
    'Dentistry': 8,
    'Digital Marketing': 7,
    'Economics': 9,
    'Education': 7,
    'Electrical Engineering': 8,
    'Energy': 7,
    'Engineering': 9,
    'Environmental Science': 8,
    'Fashion': 6,
    'Finance': 9,
    'Food Science': 7,
    'Game Development': 7,
    'Genetics': 8,
    'Graphic Design': 6,
    'Healthcare': 8,
    'Hospitality': 7,
    'Human Resources': 7,
    'Information Technology': 10,
    'Insurance': 7,
    'Interior Design': 7,
    'International Relations': 8,
    'Journalism': 7,
    'Law': 9,
    'Linguistics': 7,
    'Logistics': 7,
    'Management': 10,
    'Marketing': 9,
    'Mathematics': 8,
    'Mechanical Engineering': 8,
    'Medicine': 9,
    'Music': 7,
    'Nursing': 8,
    'Nutrition': 7,
    'Pharmacy': 8,
    'Philosophy': 7,
    'Physics': 8,
    'Political Science': 8,
    'Product Management': 8,
    'Psychology': 8,
    'Public Relations': 7,
    'Real Estate': 7,
    'Robotics': 8,
    'Social Media': 7,
    'Sociology': 7,
    'Software Development': 10,
    'Statistics': 8,
    'Supply Chain': 7,
    'Sustainability': 8,
    'Telecommunications': 7,
    'User Experience (UX)': 8,
    'Web Development': 10,
}

education_level_keyword = {
    'HSD': ['lukio','High School Diploma', 'Secondary School Certificate', 'Secondary Education'],
    'AD': ['Associate Degree', '2-Year Degree', 'Community College Degree'],
    'BD': ['Bachelor\'s Degree', 'Undergraduate Degree', '4-Year Degree'],
    'MD': ['Master\'s Degree', 'Graduate Degree', 'Postgraduate Degree'],
    'MSc': ['MSc', 'Master of Science'],
    'MBA': ['MBA', 'Master of Business Administration'],
    'PhD': ['PhD', 'Doctor of Philosophy'],
    'DD': ['Doctorate Degree', 'Doctoral Degree'],
    'PD': ['Postdoctoral Degree', 'Postdoc'],
    'Prof': ['Professional Degree', 'Professional Certification'],
    'CP': ['Certificate Program', 'Certification Program', 'Vocational Certificate'],
    'VT': ['Vocational Training', 'Trade School', 'Technical School'],
    'TD': ['Technical Degree', 'Technology Degree', 'Applied Science Degree'],
    'TS': ['Trade School', 'Trade Certificate', 'Skilled Trades Training'],
    'Diploma': ['Diploma', 'Certificate', 'Graduation Certificate'],
    'UG': ['Undergraduate', 'Bachelor\'s Level'],
    'Grad': ['Graduate', 'Postgraduate'],
    'Law': ['Law Degree', 'Juris Doctor', 'J.D.'],
    'MD': ['Medical Degree', 'Doctor of Medicine', 'M.D.'],
    'Engg': ['Engineering Degree', 'Bachelor of Engineering', 'B.Eng.'],
    'Nursing': ['Nursing Degree', 'Bachelor of Nursing', 'B.N.'],
    'Arch': ['Architecture Degree', 'Bachelor of Architecture', 'B.Arch.'],
    'Art': ['Art Degree', 'Bachelor of Fine Arts', 'B.F.A.'],
    'Music': ['Music Degree', 'Bachelor of Music', 'B.Mus.'],
    'Theatre': ['Theatre Degree', 'Bachelor of Theatre Arts', 'B.T.A.'],
    'Film': ['Film Degree', 'Bachelor of Film Production', 'B.F.P.'],
    'Design': ['Design Degree', 'Bachelor of Design', 'B.Des.'],
    'Ed': ['Education Degree', 'Bachelor of Education', 'B.Ed.'],
    'SW': ['Social Work Degree', 'Bachelor of Social Work', 'B.S.W.'],
    'Psych': ['Psychology Degree', 'Bachelor of Psychology', 'B.Psych.'],
    'Counseling': ['Counseling Degree', 'Bachelor of Counseling', 'B.Couns.'],
    'Bus': ['Business Degree', 'Bachelor of Business', 'B.B.A.'],
    'Accounting': ['Accounting Degree', 'Bachelor of Accounting', 'B.Acc.'],
    'Finance': ['Finance Degree', 'Bachelor of Finance', 'B.Fin.'],
    'Mkt': ['Marketing Degree', 'Bachelor of Marketing', 'B.Mkt.'],
    'CS': ['Computer Science Degree', 'Bachelor of Computer Science', 'B.Comp.Sc.'],
    'IT': ['Information Technology Degree', 'Bachelor of Information Technology', 'B.I.T.'],
    'DataSci': ['Data Science Degree', 'Bachelor of Data Science', 'B.D.S.'],
    'CyberSec': ['Cybersecurity Degree', 'Bachelor of Cybersecurity', 'B.C.S.'],
}

education_ratings = {
    'HSD': 3,
    'AD': 4,
    'BD': 6,
    'MD': 8,
    'MSc': 8,
    'MBA': 9,
    'PhD': 10,
    'DD': 10,
    'PD': 8,
    'Prof': 7,
    'CP': 4,
    'VT': 3,
    'TD': 5,
    'TS': 4,
    'Diploma': 3,
    'UG': 5,
    'Grad': 7,
    'Law': 9,
    'MD': 9,
    'Engg': 8,
    'Nursing': 6,
    'Arch': 7,
    'Art': 6,
    'Music': 6,
    'Theatre': 6,
    'Film': 6,
    'Design': 6,
    'Ed': 6,
    'SW': 7,
    'Psych': 6,
    'Counseling': 6,
    'Bus': 7,
    'Accounting': 6,
    'Finance': 7,
    'Mkt': 7,
    'CS': 8,
    'IT': 7,
    'DataSci': 8,
    'CyberSec': 8,
}
